#!/usr/bin/env bash

# ------------------------------------------------------
# AutoM8 Variables
# ------------------------------------------------------
DISTRO=$(lsb_release -si 2>/dev/null)
CODENAME=$(lsb_release -sc 2>/dev/null)
RELEASE=$(lsb_release -sr 2>/dev/null)
ARCH=$(uname -m)
USER=$(whoami)
HOME=$(eval echo ~$USER)
INSTALL_DIR="/opt/AutoM8"
APPS_DIR="$INSTALL_DIR/apps"
LOG_DIR="$INSTALL_DIR/log"
LOG_FILE="$INSTALL_DIR/$LOG_DIR/autom8.log"
LOG_INSTALL="$INSTALL_DIR/$LOG_DIR/install.log"
LOG_APPS="$INSTALL_DIR/$LOG_DIR/apps.log"
DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------
# Colors
# ------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
WHITE='\033[0;37m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
LIGHTYELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
WHITEBOLD='\033[1;37m'
NC='\033[0m' # No Color

export RED GREEN YELLOW BLUE WHITE LIGHTRED LIGHTGREEN LIGHTYELLOW LIGHTBLUE WHITEBOLD NC