#!/usr/bin/env bash

autom8_load_config() {
  if [[ ! -f "$AUTOM8_CONFIG_FILE" && -f "$AUTOM8_CONFIG_EXAMPLE" ]]; then
    cp "$AUTOM8_CONFIG_EXAMPLE" "$AUTOM8_CONFIG_FILE"
  fi

  if [[ -f "$AUTOM8_CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$AUTOM8_CONFIG_FILE"
  fi

  AUTOM8_LANGUAGE="${AUTOM8_LANGUAGE:-pt-BR}"
  AUTOM8_MODE="${AUTOM8_MODE:-safe}"
  AUTOM8_DEFAULT_CLEAN_LEVEL="${AUTOM8_DEFAULT_CLEAN_LEVEL:-safe}"
  AUTOM8_LOG_RETENTION_DAYS="${AUTOM8_LOG_RETENTION_DAYS:-30}"
  AUTOM8_BACKUP_KEEP="${AUTOM8_BACKUP_KEEP:-2}"
  AUTOM8_DEFAULT_BACKUP_DIR="${AUTOM8_DEFAULT_BACKUP_DIR:-$AUTOM8_BACKUP_DIR}"
  AUTOM8_REPORT_FORMAT="${AUTOM8_REPORT_FORMAT:-txt}"
  AUTOM8_ALLOW_UNSUPPORTED_DIAGNOSTIC_ONLY="${AUTOM8_ALLOW_UNSUPPORTED_DIAGNOSTIC_ONLY:-true}"
}

autom8_save_config() {
  cat > "$AUTOM8_CONFIG_FILE" <<EOF_CONF
AUTOM8_LANGUAGE="$AUTOM8_LANGUAGE"
AUTOM8_MODE="$AUTOM8_MODE"
AUTOM8_DEFAULT_CLEAN_LEVEL="$AUTOM8_DEFAULT_CLEAN_LEVEL"
AUTOM8_LOG_RETENTION_DAYS="$AUTOM8_LOG_RETENTION_DAYS"
AUTOM8_BACKUP_KEEP="$AUTOM8_BACKUP_KEEP"
AUTOM8_DEFAULT_BACKUP_DIR="$AUTOM8_DEFAULT_BACKUP_DIR"
AUTOM8_REPORT_FORMAT="$AUTOM8_REPORT_FORMAT"
AUTOM8_ALLOW_UNSUPPORTED_DIAGNOSTIC_ONLY="$AUTOM8_ALLOW_UNSUPPORTED_DIAGNOSTIC_ONLY"
EOF_CONF
}
